name: Code Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Clonar el repositorio
    - name: Checkout code
      uses: actions/checkout@v3

    # Paso 2: Configurar Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    # Paso 3: Instalar dependencias
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyautogui
        pip install pytest pytest-cov coverage

    - name: Install xvfb
      run: sudo apt-get install -y xvfb
    - name: Start xvfb
      run: |
        Xvfb :99 -screen 0 1024x768x16 &
        echo "Xvfb started"

    # Paso 4: Ejecutar pruebas con cobertura
    - name: Run tests with coverage
      env:
        DISPLAY: :99
      run: |
        pytest --cov=ahorcado --cov-report=xml
        pytest --cov=AhorcadoApp --cov-report=xml

    # Paso 5: Mostrar reporte de cobertura en consola
    - name: Display coverage report
      run: coverage report

    # Paso 6: Subir reporte de cobertura como artefacto
    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage.xml
